red_team: ["moliveira", "jfigueiredo", "sinacio", "mgomes"]
green_team: ["dfigueiredo", "rdcosta", "rcosta", "dnunes"]
blue_team: ["dalmeida", "fcurado", "tavila"]

hunting_distance: 0.5
game_duration: 60
immunity_duration: 3
killed_duration: 6
positive_score: 1
negative_score: -1
best_hunter_score: 5
best_survivor_score: 5